### ISSUE TITLE
Build and Load on Fabric with Fabric API 0.92.0+1.20.1 crashes

### ISSUE THREAD

**Issue by flufferyomada** [moomooooo/postman#58]
When building this is produced after running `genSources`
```
warning: unknown enum constant Status.MAINTAINED
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
/home/fluffery/postman/src/main/java/me/srgantmoomoo/postman/mixins/MixinClientConnection.java:22: warning: Cannot find target method "send(Lnet/minecraft/network/Packet;)V" for @Inject.method="send(Lnet/minecraft/network/Packet;)V" in net.minecraft.network.ClientConnection
    @Inject(method = "send(Lnet/minecraft/network/Packet;)V", at = @At("HEAD"), cancellable = true)
    ^
warning: unknown enum constant Status.MAINTAINED
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.MAINTAINED
  reason: class file for org.apiguardian.api.API$Status not found
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.STABLE
warning: unknown enum constant Status.EXPERIMENTAL
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.MAINTAINED
warning: unknown enum constant Status.EXPERIMENTAL
98 warnings
```
still said successful

```
[12:33:18] [Render thread/ERROR]: Mixin apply for mod postman failed postman.mixins.json:MixinClientConnection from mod postman -> net.minecraft.class_2535: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on send could not find any targets matching 'Lnet/minecraft/class_2535;send(Lnet/minecraft/network/Packet;)V' in net.minecraft.class_2535. Using refmap postman-refmap.json [PREINJECT Applicator Phase -> postman.mixins.json:MixinClientConnection from mod postman -> Prepare Injections ->  -> handler$zlh000$postman$send(Lnet/minecraft/class_2596;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on send could not find any targets matching 'Lnet/minecraft/class_2535;send(Lnet/minecraft/network/Packet;)V' in net.minecraft.class_2535. Using refmap postman-refmap.json [PREINJECT Applicator Phase -> postman.mixins.json:MixinClientConnection from mod postman -> Prepare Injections ->  -> handler$zlh000$postman$send(Lnet/minecraft/class_2596;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:656) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:587) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at jdk.internal.reflect.GeneratedConstructorAccessor21.newInstance(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:708) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) ~[sponge-mixin-0.12.5 mixin.0.8.5.jar:0.12.5 mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.15.7.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?]
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?]
	at java.lang.Class.getDeclaredMethods(Class.java:2504) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:68) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:384) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) ~[fabric-loader-0.15.7.jar:?]
	at net.minecraft.client.MinecraftClient.<init>(MinecraftClient.java:458) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:211) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.7.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.7.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:87) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:129) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:70) ~[NewLaunch.jar:?]
```

Video of me building it:
https://www.youtube.com/watch?v=3SvT-5FC7KA

i also proudly use github as a file dump

**Comment by srgantmoomoo** [comment]
crashes* really not failure woops. that should work though... you can close the issue if so, if not then let me know.

**Comment by flufferyomada** [comment]
ok i got it to build, i'm gonna contribute some horrible code that will cause many issues later
